---
title: "Take Home Exercise 4"
description: |
  This weeks exercise is about scirpting and visualising financial data from yahoo
  finance."
author:
  - name: Sean Samuel Prajs
    url: https://github.com/SeanP0110
    affiliation: SMU
date: "2022/02/27"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    code_folding: true
---
Today we will be scripting financial data from yahoo finance and creating a horizon 8plot
using gghorigraph

# Data Upload

```{r, echo=TRUE,eval=TRUE}
packages = c('tidyquant','tidyverse','data.table','ggHoriPlot','ggplot2',
             'XML','xml2','httr','rmarkdown','knitr','ggthemes')
for (p in packages) {
  if(!require(p,character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

# Scripting
```{r, echo=TRUE,eval=TRUE}
from_date = "2020-01-01"
to_date = "2021-12-31"
period_type = "days"  # "days"/ "weeks"/ "months"/ "years"

stocks <- c("SE","DBSDF","O39.SI","U11.SI","SNGNF","GRAB","WLMIF","SINGF",
            "C38U.SI","A17U.SI","SJX.F","BN4.SI","FLEX","SPXCF","G07.SI",
            "G13.SI","C07.SI","2588.HK","M44U.SI","ME8U.SI","C09.SI","O32.SI",
            "N2IU.SI","U14.SI","BUOU.SI","T82U.SI","U96.SI","S58.SI","KLIC",
            "K71U.SI","KEN","RW0U.SI","CJLU.SI","U06.SI","C52.SI","TDCX",
            "HCTPF","Z25.SI","KARO","TRIT")


stock_price <- function(from,to,pt,stock){
  s <- tq_get(stock,
         get = "stock.prices",
         from = from_date,
         to = to_date) %>%tq_transmute(select     = NULL, 
                                       mutate_fun = to.period, 
                                       period  = period_type)
  stock <- paged_table(s)
  return(data.frame(stock))
}
```

# Graph
```{r, echo=TRUE,eval=TRUE}
all_stocks <- stock_price(from_date,to_date,period_type,stocks[1])
all_stocks$CompanyName <- stocks[1]


for (stock in stocks[2:40]){
  df <- stock_price(from_date,to_date,period_type,stock)
  df$CompanyName <- stock
  all_stocks = rbind(all_stocks,df)
}



unique(all_stocks$CompanyName)


cutpoints <- function(stock){
  stock  %>% 
  mutate(
    outlier = between(
      close, 
      quantile(close, 0.25, na.rm=T)-
        1.5*IQR(close, na.rm=T),
      quantile(close, 0.75, na.rm=T)+
        1.5*IQR(close, na.rm=T))) %>% 
  filter(outlier)
}

ori <- sum(range(cutpoints(all_stocks)$close))/2
sca <- seq(range(cutpoints(all_stocks)$close)[1], 
           range(cutpoints(all_stocks)$close)[2], 
           length.out = 7)[-4]

round(ori, 2)
round(sca, 2) 

all_stocks %>% ggplot() +
  geom_horizon(aes(date, 
                   close,
                   fill = ..Cutpoints..), 
               origin = ori, horizonscale = sca) +
  scale_fill_hcl(palette = 'RdBu', reverse = T) +
  facet_grid(CompanyName~.) +
  theme_few() +
  theme(
    panel.spacing.y=unit(0, "lines"),
    strip.text.y = element_text(size = 7, angle = 0, hjust = 0),
    axis.text.y = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.border = element_blank()
  ) +
  scale_x_date(expand=c(0,0), 
               date_breaks = "1 month", 
               date_labels = "%b") +
  xlab('Date') +
  ggtitle('SG Main Stock Prices 2020-2022')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web. 

Learn more about using Distill for R Markdown at <https://rstudio.github.io/distill>.





